development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  host: localhost
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  host: localhost
  pool: 5
  username: postgres
  password: password
